use_frameworks!

target 'JSONModel.swift_Example' do
  pod 'JSONModel.swift', :path => '../'

  pod 'SwiftyJSON'

  target 'JSONModel.swift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
